List<Map<String,dynamic>> places = [
  {
    "id"  : 1,
    "name":"Germany",
    "image1":"assets/image/img_2.png",
    "image2":"assets/image/img_1.png",
    "place1":"assets/image/img_6.png",
    "place2":"assets/image/img_5.png",
    "place3":"assets/image/img_8.png",
    "place4":"assets/image/img_7.png",
    "place5":"assets/image/img_9.png",
    "place0":"assets/image/img_6.png",
    "description": "Germany,[e] officially the Federal Republic of Germany,[f] is a country in Central Europe. It is the second-most populous country in Europe after Russia, and the most populous member state of the European Union."
  },
  {
    "id"  : 2,
    "name":"Italy",
    "image1":"assets/image/img_2.png",
    "image2":"assets/image/img_2.png",
    "place1":"assets/image/img_2.png",
    "place2":"assets/image/img_2.png",
    "place3":"assets/image/img_2.png",
    "place4":"assets/image/img_2.png",
    "place5":"assets/image/img_2.png",
    "place0":"assets/image/img_2.png",
    "description": "Italy (Italian: Italia [iˈtaːlja] (listen)), officially the Italian Republic[a][12][13] or the Republic of Italy,[14][15] is a country in Southern[16][17][18] and Western[19][note 1] Europe. Located in the middle of the Mediterranean Sea, it consists of a peninsula delimited by the Alps and surrounded by several islands.[20] Italy shares land borders with France, Switzerland, Austria, Slovenia and the enclaved microstates of Vatican City and San Marino. "
  },
  {
    "id"  : 3,
    "name":"Spain",
    "image1":"assets/image/img_2.png",
    "image2":"assets/image/img_2.png",
    "place1":"assets/image/img_2.png",
    "place2":"assets/image/img_2.png",
    "place3":"assets/image/img_2.png",
    "place4":"assets/image/img_2.png",
    "place5":"assets/image/img_2.png",
    "place0":"assets/image/img_2.png",
    "description": "Spain (Spanish: España, [esˈpaɲa] (listen)), or the Kingdom of Spain (Reino de España),[f] is a country located in Southwestern Europe, with parts of its territory in the Atlantic Ocean and across the Mediterranean Sea."
  },
  {
    "id"  : 4,
    "name":"India",
    "image1":"assets/image/img_2.png",
    "image2":"assets/image/img_2.png",
    "place1":"assets/image/img_2.png",
    "place2":"assets/image/img_2.png",
    "place3":"assets/image/img_2.png",
    "place4":"assets/image/img_2.png",
    "place5":"assets/image/img_2.png",
    "place0":"assets/image/img_2.png",
    "description": "India, officially the Republic of India (ISO: Bhārat Gaṇarājya),[22] is a country in South Asia. It is the seventh-largest country by area; the most populous country as of June 2023;[23][24] and from the time of its independence in 1947, the world's most populous democracy."},
  {
    "id"  : 5,
    "name":"UAE",
    "image1":"assets/image/img_2.png",
    "image2":"assets/image/img_2.png",
    "place1":"assets/image/img_2.png",
    "place2":"assets/image/img_2.png",
    "place3":"assets/image/img_2.png",
    "place4":"assets/image/img_2.png",
    "place5":"assets/image/img_2.png",
    "place0":"assets/image/img_2.png",
    "description": "The United Arab Emirates (UAE; Arabic: الإمارات العربية المتحدة al-ʾImārāt al-ʿArabiyya l-Muttaḥida[note 2]), or simply the Emirates (Arabic: الإمارات al-ʾImārāt), is a country in West Asia, in the Middle East. It is located at the eastern end of the Arabian Peninsula and shares borders with Oman and Saudi Arabia"
  },
];